### ISSUE TITLE
no /OCR command

### ISSUE THREAD

**Issue by happy15** [xxchan/logseq-ocr#2]
Hi there, I installed this plugin from plugin market and restarted my logseq. However, after enter "/ocr" no "OCR from clipboard" showed in the popup menu. Anything did I miss? Thanks.

**Comment by xxchan** [comment]
Can you try uninstall & reinstall? I reproduced it just now, and fixed it in this way, but don't know why :)

**Comment by happy15** [comment]
Works like a charm, though don't know why :)

Thanks
